In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [57]:
params = {'legend.fontsize': 'x-large',  # Configuration for matplotlib
          'figure.figsize': (20, 20),
         'axes.labelsize': 'x-large',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'x-large',
         'ytick.labelsize':'x-large'}
plt.rcParams.update(params)

In [58]:
alarms = pd.read_csv("LDT_Alarm_Log.csv")
data = pd.read_csv("LDT-1Hz-Met-2017-02.csv")
alarms.head()

,LastUpdated,Source,TimeOn,TimeOff,Asset,EventIndex,EventCode,EventDescription,EventCategory,Duration,TimeOnBin,TimeOnBin_P1,TimeOffBin_M1,TimeOffBin
0,2017-02-14 04:00:40.510,asset,2016-07-13 16:19:51.187,2016-07-13 16:19:59.277,WTG01,97.01,97.0,Yaw Error > Max Start Yaw Error,3.0,8.0,2016-07-13 16:20:00.000,2016-07-13 16:30:00.000,2016-07-13 16:10:00.000,2016-07-13 16:20:00.000
1,2017-02-14 04:00:40.510,asset,2016-07-13 17:10:19.010,2016-07-13 17:14:23.920,WTG01,97.01,97.0,Yaw Error > Max Start Yaw Error,3.0,244.0,2016-07-13 17:20:00.000,2016-07-13 17:30:00.000,2016-07-13 17:10:00.000,2016-07-13 17:20:00.000
2,2017-02-14 04:00:40.510,asset,2016-07-13 19:03:48.280,2016-07-13 19:04:22.610,WTG01,1035.01,1035.0,PitchMotorPtcOk22,9.0,34.0,2016-07-13 19:10:00.000,2016-07-13 19:20:00.000,2016-07-13 19:00:00.000,2016-07-13 19:10:00.000
3,2017-02-14 04:00:40.510,asset,2016-07-14 02:45:05.307,2016-07-14 02:45:39.857,WTG01,896.01,896.0,PitchMotorPtcOk11,9.0,34.0,2016-07-14 02:50:00.000,2016-07-14 03:00:00.000,2016-07-14 02:40:00.000,2016-07-14 02:50:00.000
4,2017-02-14 04:00:40.510,asset,2016-07-14 03:10:02.180,2016-07-14 03:10:33.733,WTG01,435.01,435.0,Pitch System Fatal Error,9.0,31.0,2016-07-14 03:20:00.000,2016-07-14 03:30:00.000,2016-07-14 03:10:00.000,2016-07-14 03:20:00.000

In [59]:
data.head()

,TimeStamp,IsTrigger,Wet,Barometer_2,Barmoeter_1,temp_2,temp_1,WindVane_2,WindVane_1,Anemo_4,Anemo_3,Anemo_2,Anemo_1,temp_T,WindVane_T,Anemo_T
0,2017-02-01 00:00:00.230,1,4.727232e-30,1027.543,1004.572,5.78295,6.85110,177.4375,179.3434,0.7583,0.7178,1.1762,1.1852,8.499988,250.519,1.128378
1,2017-02-01 00:00:01.231,0,5.062639e+04,1027.580,1004.572,5.78295,6.85415,177.0859,178.6402,0.7583,0.7178,1.2222,1.1852,8.499988,250.519,1.095191
2,2017-02-01 00:00:02.253,0,4.727232e-30,1027.543,1004.590,5.78600,6.85110,177.0859,179.3434,0.8043,0.7178,1.1762,1.1852,8.499988,250.519,1.128378
3,2017-02-01 00:00:03.264,0,4.727232e-30,1027.580,1004.572,5.78295,6.85720,176.7344,178.6402,0.7583,0.7178,1.2222,1.1852,8.499988,250.519,1.086036
4,2017-02-01 00:00:04.305,0,-5.106113e+13,1027.543,1004.572,5.79516,6.85415,176.7344,177.9371,0.8043,0.7178,1.2222,1.2311,8.499988,250.519,1.081458

In [60]:
alarms["TimeOn"] = pd.to_datetime(alarms["TimeOn"])
data["TimeStamp"] = pd.to_datetime(data["TimeStamp"])
alarms.index =  pd.to_datetime(alarms["TimeOn"])
data.index =  pd.to_datetime(data["TimeStamp"])

In [61]:
tolerance = pd.Timedelta("1 second")

In [62]:
alarms = alarms.sort_index()

In [63]:
merged = pd.merge_asof(data, alarms, left_index=True, right_index=True, direction="nearest", tolerance=tolerance)
merged.sort_index()

,TimeStamp,IsTrigger,Wet,Barometer_2,Barmoeter_1,temp_2,temp_1,WindVane_2,WindVane_1,Anemo_4,...,Asset,EventIndex,EventCode,EventDescription,EventCategory,Duration,TimeOnBin,TimeOnBin_P1,TimeOffBin_M1,TimeOffBin
TimeStamp,,,,,,,,,,,,,,,,,,,,,
2017-02-01 00:00:00.230,2017-02-01 00:00:00.230,1,4.727232e-30,1027.543,1004.5720,5.78295,6.85110,177.4375,179.3434,0.7583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:01.231,2017-02-01 00:00:01.231,0,5.062639e+04,1027.580,1004.5720,5.78295,6.85415,177.0859,178.6402,0.7583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:02.253,2017-02-01 00:00:02.253,0,4.727232e-30,1027.543,1004.5900,5.78600,6.85110,177.0859,179.3434,0.8043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:03.264,2017-02-01 00:00:03.264,0,4.727232e-30,1027.580,1004.5720,5.78295,6.85720,176.7344,178.6402,0.7583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:04.305,2017-02-01 00:00:04.305,0,-5.106113e+13,1027.543,1004.5720,5.79516,6.85415,176.7344,177.9371,0.8043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-28 23:59:55.608,2017-02-28 23:59:55.608,0,-1.569609e-22,1016.373,988.1283,2.01392,3.51543,279.0391,281.6481,6.7765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-28 23:59:56.629,2017-02-28 23:59:56.629,0,-9.223372e+18,1016.373,988.1283,2.02002,3.52458,279.0391,281.6481,6.7305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-28 23:59:57.630,2017-02-28 23:59:57.630,0,-1.569609e-22,1016.373,987.9635,2.02002,3.50932,278.6875,281.9996,6.5008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-28 23:59:58.652,2017-02-28 23:59:58.652,0,-1.571217e-04,1016.373,988.1283,2.02002,3.54595,278.6875,281.6481,6.7305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-28 23:59:59.693,2017-02-28 23:59:59.693,0,-9.223372e+18,1016.373,987.9452,2.00781,3.53069,279.0391,280.9449,6.7305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
merged.keys

<bound method NDFrame.keys of                                       TimeStamp  IsTrigger           Wet  \
TimeStamp
2017-02-01 00:00:00.230 2017-02-01 00:00:00.230          1  4.727232e-30
2017-02-01 00:00:01.231 2017-02-01 00:00:01.231          0  5.062639e+04
2017-02-01 00:00:02.253 2017-02-01 00:00:02.253          0  4.727232e-30
2017-02-01 00:00:03.264 2017-02-01 00:00:03.264          0  4.727232e-30
2017-02-01 00:00:04.305 2017-02-01 00:00:04.305          0 -5.106113e+13
...                                         ...        ...           ...
2017-02-28 23:59:55.608 2017-02-28 23:59:55.608          0 -1.569609e-22
2017-02-28 23:59:56.629 2017-02-28 23:59:56.629          0 -9.223372e+18
2017-02-28 23:59:57.630 2017-02-28 23:59:57.630          0 -1.569609e-22
2017-02-28 23:59:58.652 2017-02-28 23:59:58.652          0 -1.571217e-04
2017-02-28 23:59:59.693 2017-02-28 23:59:59.693          0 -9.223372e+18

                         Barometer_2  Barmoeter_1   temp_2   temp_1  \
TimeStamp
2017-02-01 00:00:00.230     1027.543    1004.5720  5.78295  6.85110
2017-02-01 00:00:01.231     1027.580    1004.5720  5.78295  6.85415
2017-02-01 00:00:02.253     1027.543    1004.5900  5.78600  6.85110
2017-02-01 00:00:03.264     1027.580    1004.5720  5.78295  6.85720
2017-02-01 00:00:04.305     1027.543    1004.5720  5.79516  6.85415
...                              ...          ...      ...      ...
2017-02-28 23:59:55.608     1016.373     988.1283  2.01392  3.51543
2017-02-28 23:59:56.629     1016.373     988.1283  2.02002  3.52458
2017-02-28 23:59:57.630     1016.373     987.9635  2.02002  3.50932
2017-02-28 23:59:58.652     1016.373     988.1283  2.02002  3.54595
2017-02-28 23:59:59.693     1016.373     987.9452  2.00781  3.53069

                         WindVane_2  WindVane_1  Anemo_4  ...  Asset  \
TimeStamp                                                 ...
2017-02-01 00:00:00.230    177.4375    179.3434   0.7583  ...    NaN
2017-02-01 00:00:01.231    177.0859    178.6402   0.7583  ...    NaN
2017-02-01 00:00:02.253    177.0859    179.3434   0.8043  ...    NaN
2017-02-01 00:00:03.264    176.7344    178.6402   0.7583  ...    NaN
2017-02-01 00:00:04.305    176.7344    177.9371   0.8043  ...    NaN
...                             ...         ...      ...  ...    ...
2017-02-28 23:59:55.608    279.0391    281.6481   6.7765  ...    NaN
2017-02-28 23:59:56.629    279.0391    281.6481   6.7305  ...    NaN
2017-02-28 23:59:57.630    278.6875    281.9996   6.5008  ...    NaN
2017-02-28 23:59:58.652    278.6875    281.6481   6.7305  ...    NaN
2017-02-28 23:59:59.693    279.0391    280.9449   6.7305  ...    NaN

                         EventIndex  EventCode  EventDescription  \
TimeStamp
2017-02-01 00:00:00.230         NaN        NaN               NaN
2017-02-01 00:00:01.231         NaN        NaN               NaN
2017-02-01 00:00:02.253         NaN        NaN               NaN
2017-02-01 00:00:03.264         NaN        NaN               NaN
2017-02-01 00:00:04.305         NaN        NaN               NaN
...                             ...        ...               ...
2017-02-28 23:59:55.608         NaN        NaN               NaN
2017-02-28 23:59:56.629         NaN        NaN               NaN
2017-02-28 23:59:57.630         NaN        NaN               NaN
2017-02-28 23:59:58.652         NaN        NaN               NaN
2017-02-28 23:59:59.693         NaN        NaN               NaN

                         EventCategory  Duration TimeOnBin TimeOnBin_P1  \
TimeStamp
2017-02-01 00:00:00.230            NaN       NaN       NaN          NaN
2017-02-01 00:00:01.231            NaN       NaN       NaN          NaN
2017-02-01 00:00:02.253            NaN       NaN       NaN          NaN
2017-02-01 00:00:03.264            NaN       NaN       NaN          NaN
2017-02-01 00:00:04.305            NaN       NaN       NaN          NaN
...                                ...       ...       ...          ...
2017-02-28 23:59:55.608            NaN       NaN       NaN          NaN
2017-02-28 23:59:56.629            NaN       NaN       NaN          NaN
2017-02-28 23:59:57.630            NaN       NaN       NaN          NaN
2017-02-28 23:59:58.652            NaN       NaN       NaN          NaN
2017-02-28 23:59:59.693            NaN       NaN       NaN          NaN

                        TimeOffBin_M1 TimeOffBin
TimeStamp
2017-02-01 00:00:00.230           NaN        NaN
2017-02-01 00:00:01.231           NaN        NaN
2017-02-01 00:00:02.253           NaN        NaN
2017-02-01 00:00:03.264           NaN        NaN
2017-02-01 00:00:04.305           NaN        NaN
...                               ...        ...
2017-02-28 23:59:55.608           NaN        NaN
2017-02-28 23:59:56.629           NaN        NaN
2017-02-28 23:59:57.630           NaN        NaN
2017-02-28 23:59:58.652           NaN        NaN
2017-02-28 23:59:59.693           NaN        NaN

[2371842 rows x 30 columns]>

In [65]:
merged.groupby("EventCode").head()

,TimeStamp,IsTrigger,Wet,Barometer_2,Barmoeter_1,temp_2,temp_1,WindVane_2,WindVane_1,Anemo_4,...,Asset,EventIndex,EventCode,EventDescription,EventCategory,Duration,TimeOnBin,TimeOnBin_P1,TimeOffBin_M1,TimeOffBin
TimeStamp,,,,,,,,,,,,,,,,,,,,,
2017-02-01 00:00:00.230,2017-02-01 00:00:00.230,1,4.727232e-30,1027.543,1004.5720,5.78295,6.85110,177.4375,179.3434,0.7583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:01.231,2017-02-01 00:00:01.231,0,5.062639e+04,1027.580,1004.5720,5.78295,6.85415,177.0859,178.6402,0.7583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:02.253,2017-02-01 00:00:02.253,0,4.727232e-30,1027.543,1004.5900,5.78600,6.85110,177.0859,179.3434,0.8043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:03.264,2017-02-01 00:00:03.264,0,4.727232e-30,1027.580,1004.5720,5.78295,6.85720,176.7344,178.6402,0.7583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:04.305,2017-02-01 00:00:04.305,0,-5.106113e+13,1027.543,1004.5720,5.79516,6.85415,176.7344,177.9371,0.8043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-27 20:21:33.961,2017-02-27 20:21:33.961,0,-1.569609e-22,1009.281,977.1783,3.18278,3.04849,307.5156,309.7731,3.3769,...,WTG01,99.01,99.0,Software Cable Twist CCW,3.0,635.0,2017-02-27 20:30:00.000,2017-02-27 20:40:00.000,2017-02-27 20:30:00.000,2017-02-27 20:40:00.000
2017-02-27 20:21:34.973,2017-02-27 20:21:34.973,0,-1.569609e-22,1009.281,976.9768,3.18583,3.04849,306.8125,309.4215,3.2850,...,WTG01,99.01,99.0,Software Cable Twist CCW,3.0,635.0,2017-02-27 20:30:00.000,2017-02-27 20:40:00.000,2017-02-27 20:30:00.000,2017-02-27 20:40:00.000
2017-02-27 20:32:09.245,2017-02-27 20:32:09.245,0,-1.571217e-04,1009.293,977.1783,3.01798,3.05460,299.7812,302.0387,3.8363,...,WTG01,296.01,296.0,Yaw Brake 2 Failed To Release,9.0,4.0,2017-02-27 20:40:00.000,2017-02-27 20:50:00.000,2017-02-27 20:30:00.000,2017-02-27 20:40:00.000
2017-02-27 20:32:13.321,2017-02-27 20:32:13.321,0,-1.571217e-04,1009.330,976.9768,3.01492,3.05155,300.4844,302.7418,3.8363,...,WTG01,99.01,99.0,Software Cable Twist CCW,3.0,3.0,2017-02-27 20:40:00.000,2017-02-27 20:50:00.000,2017-02-27 20:30:00.000,2017-02-27 20:40:00.000
2017-02-27 20:32:14.342,2017-02-27 20:32:14.342,0,-9.223372e+18,1009.293,976.9951,3.01798,3.03323,299.7812,302.0387,4.0201,...,WTG01,99.01,99.0,Software Cable Twist CCW,3.0,3.0,2017-02-27 20:40:00.000,2017-02-27 20:50:00.000,2017-02-27 20:30:00.000,2017-02-27 20:40:00.000

In [69]:
errs = list(merged["EventCode"])
counter = 0
pointer = 0
time_til_err = []
for err in errs:
    if np.isnan(err):
        counter += 1
    else:  
        for i in range(counter, 0, -1):
            time_til_err.append(int(i))
        counter = 0
    pointer += 1

diff = pointer - len(time_til_err)
for i in range(0, diff):
    time_til_err.append(np.nan)

In [70]:
merged.insert(1, "TimeUntilAlarm", time_til_err, True)
merged.head()

,TimeStamp,TimeUntilAlarm,TimeUntilAlarm,TimeUntilAlarm,IsTrigger,Wet,Barometer_2,Barmoeter_1,temp_2,temp_1,...,Asset,EventIndex,EventCode,EventDescription,EventCategory,Duration,TimeOnBin,TimeOnBin_P1,TimeOffBin_M1,TimeOffBin
TimeStamp,,,,,,,,,,,,,,,,,,,,,
2017-02-01 00:00:00.230,2017-02-01 00:00:00.230,1421063.0,1421063.0,1421063.0,1,4.727232e-30,1027.543,1004.572,5.78295,6.85110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:01.231,2017-02-01 00:00:01.231,1421062.0,1421062.0,1421062.0,0,5.062639e+04,1027.580,1004.572,5.78295,6.85415,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:02.253,2017-02-01 00:00:02.253,1421061.0,1421061.0,1421061.0,0,4.727232e-30,1027.543,1004.590,5.78600,6.85110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:03.264,2017-02-01 00:00:03.264,1421060.0,1421060.0,1421060.0,0,4.727232e-30,1027.580,1004.572,5.78295,6.85720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01 00:00:04.305,2017-02-01 00:00:04.305,1421059.0,1421059.0,1421059.0,0,-5.106113e+13,1027.543,1004.572,5.79516,6.85415,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
plt.figure()
plt.title("General Cortime_til_errions for data")
corr = merged.corr()
sns.heatmap(corr)
plt.show()